version: "3.9"

services:
  db:
    image: postgres:15
    container_name: estufas_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estufas_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: estufas_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@estufas.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - estufas_net

  app:
    build: ./backend
    container_name: estufas_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8501:8501"
    volumes:
      - ./backend:/app
    networks:
      - estufas_net

volumes:
  postgres_data:

networks:
  estufas_net:
